sudo: required #is required to use docker service in travis

language: generic

services:
  - docker

before_install:
  - docker --version

script:
  - DOCKER_TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH#v} ; fi)
  - docker run -it --rm -v "$PWD/Dockerfile:/Dockerfile:ro" redcoolbeans/dockerlint
  
  - docker build -t edwarddobson/docker-host:$TRAVIS_COMMIT .
  - docker tag edwarddobson/docker-host:$TRAVIS_COMMIT edwarddobson/docker-host:$DOCKER_TAG
  
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push edwarddobson/docker-host:$DOCKER_TAG
    fi
